### ISSUE TITLE
Group Ownership

### ISSUE THREAD

**Issue by csnewman** [StarMade/StarMade#24]
Could you make me an admin of the group so i can manage the group as i am planning to start doing this again? Thanks

**Comment by tambry** [comment]
@csnewman Why exactly would you need the ownership of the group? You should have the access to the full main repository already. Just asking, since I don't see how this would be a problem.

**Comment by csnewman** [comment]
As you are not actively working on this project. I was wanting the ability to create repo's but I may as well create a new group.

**Comment by tambry** [comment]
@csnewman Didn't know you wanted to create new repos, added.

**Comment by csnewman** [comment]
Thanks!

**Comment by jjaquinta** [comment]
Good luck! My current distraction is programming The Echo. But I'll answer questions if you have them.

**Comment by csnewman** [comment]
@jjaquinta Thanks, I already have got deobfuscation and reobfuscation working meaning the game is actually moddable now, I am just rewriting the remapper to be cleaner and quicker

**Comment by jjaquinta** [comment]
Well, let me know if they ever stop the stupidity of obfuscation altogether, add some extensible APIs and make the game moddable in the professional sense. :-)

**Comment by csnewman** [comment]
@jjaquinta I don't think we will be that lucky soon, even Minecraft is still obfuscated! Lets hope the api comes soon (I am unsure what is talking so long)

**Comment by jjaquinta** [comment]
Though I normally despise Microsoft, I hold a vain hope that they realize that the value of Minecraft is in the 3rd party add-ons. They have the professional experience to fix the bad parts of it being an indie game but hopefully the wisdom to retain the good parts.
But I'm not holding my breath.

**Comment by MushroomFleet** [comment]
I can tell you what takes so long for the starmade api.

It's hard and they are lazy, inexperienced and disorganised ;)

That makes for a delightful combination.

Feature creep plus hiring your mates for jobs they are not qualified for is
what made me lose interest.

I know I turned them down over a PR position and since then they have
nosedived into obscurity. I told them to hire something with a proven track
record. They chose a Youtuber with 1500 subs.

It's disappointing to watch someone repeatedly pin themselves in the face.

People told me this would happen a year ago.

ON TOPIC

I'd love to see what you do if you have managed to unobfuscate the game.

The game development has turned into a circus show where they all comparing
clown shoes now.

**Comment by jjaquinta** [comment]
>It's hard and they are lazy, inexperienced and disorganised ;)
We gotta find you something uplifting to work on, MushroomFleet! Clearly your talents would be better appreciated elsewhere.
Alas, my current project/game is for the Amazon Echo, an audio-only device. Doesn't lend itself well to YouTube videos.
Although if there was clear StarMade code I'd love to look at planetary generation. It's the area I'm most interested in, and when I tuned out, they were paying scant attention to it. But having a 3rd party add compelling content would probably only stoke their paranoia. :-)

**Comment by MushroomFleet** [comment]
Speaking as another 3rd party. Adding compelling content does indeed make
them paranoid.

I'm working a new job now and it's more enjoyable than working with Schine.

Your new project does sound awesome!

**Comment by jjaquinta** [comment]
Thanks! I have, actually, made a few YouTube videos for my Echo projects.
https://www.youtube.com/channel/UC0o-ueal1Ojk53y_aLvGiBg/videos
Watching someone talk to a black cylinder is hardly gripping though...
